openapi: 3.0.3
info:
  title: PR Risk Radar API (Copilot)
  description: PR 위험도 분석 및 성능 영향 분석을 위한 REST API
  version: 1.0.1

servers:
  - url: https://risk-radar-production.up.railway.app
    description: 프로덕션 서버

components:
  schemas:
    HealthzResponse:
      type: object
      required: [ok]
      properties:
        ok:
          type: boolean
          example: true

    ScanPrResponse:
      type: object
      required: [owner, repo, pr, score, grade]
      properties:
        owner:
          type: string
          example: Hwang9170
        repo:
          type: string
          example: Copilot_ai
        pr:
          type: integer
          example: 3
        title:
          type: string
          example: "Improve performance in fetch path"
        score:
          type: integer
          example: 72
        grade:
          type: string
          example: "B"
        signals:
          type: object
          additionalProperties: true

    AnalyzePrPerfRequest:
      type: object
      required: [owner, repo, pr]
      properties:
        owner:
          type: string
          example: Hwang9170
        repo:
          type: string
          example: Copilot_ai
        pr:
          type: integer
          example: 3

    AnalyzePrPerfResponse:
      type: object
      required: [ok, pr]
      properties:
        ok:
          type: boolean
          example: true
        pr:
          type: integer
          example: 3
        title:
          type: string
          example: "Speed up artifact download"
        complexity_analysis:
          type: object
          additionalProperties: true
        performance_risk:
          type: object
          additionalProperties: true
        summary:
          type: object
          additionalProperties: true

paths:
  /healthz:
    get:
      summary: 헬스체크
      operationId: getHealthz
      responses:
        '200':
          description: 서버 정상
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthzResponse'

  /api/scan-pr:
    get:
      summary: PR 위험도 분석
      operationId: getScanPr
      parameters:
        - name: owner
          in: query
          required: true
          schema: { type: string }
        - name: repo
          in: query
          required: true
          schema: { type: string }
        - name: pr
          in: query
          required: true
          schema: { type: integer }
      responses:
        '200':
          description: PR 위험도 분석 결과
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScanPrResponse'

  /api/analyze-pr-performance:
    post:
      summary: PR 성능 영향 분석
      operationId: postAnalyzePrPerformance
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnalyzePrPerfRequest'
      responses:
        '200':
          description: 성능 영향 분석 결과
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnalyzePrPerfResponse'
