
openapi: 3.0.3
info:
  title: PR Risk Radar API
  version: "0.1.0"
servers:
  - url: https://YOUR_PUBLIC_URL
paths:
  /healthz:
    get:
      summary: Health check
      responses:
        "200":
          description: OK
  /api/scan-pr:
    get:
      summary: Scan a pull request risk
      parameters:
        - in: query
          name: owner
          required: true
          schema: { type: string }
        - in: query
          name: repo
          required: true
          schema: { type: string }
        - in: query
          name: pr
          required: true
          schema: { type: integer }
      responses:
        "200":
          description: PR scan result
          content:
            application/json:
              schema:
                type: object
                properties:
                  owner: { type: string }
                  repo: { type: string }
                  pr: { type: integer }
                  title: { type: string }
                  state: { type: string }
                  base: { type: string }
                  draft: { type: boolean }
                  score: { type: integer }
                  grade: { type: string }
                  signals: { type: object }
